[package]
name = "pico8-like-api"
version = "0.1.0"
authors = ["gerodrus <gerodrus@gmail.com>"]
edition = "2018"

[dependencies]
sdl2-sys = "0.34.3"
rand = "0.8.1"
rand_distr = "0.4.0"

[dependencies.sdl2]
version = "0.34.3"
default-features = false
features = ["image"]
